# Generated by Django 3.2.23 on 2024-01-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objeto_deteccion_app', '0002_alter_detectedobject_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedobject',
            name='imagen',
            field=models.ImageField(upload_to='images'),
        ),
    ]
