# Generated by Django 3.2.23 on 2024-01-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objeto_deteccion_app', '0004_auto_20240111_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedobject',
            name='clase',
            field=models.IntegerField(default=0),
        ),
    ]
